/*
 * sleep.js 
 * core implementation of sleep()
 */

/*
 * Oh you've found this file!
 * Congratulations!
 * that you will probably be more confusing...
 */

var sleep = (function(){
    var first = true;
    function show_sleep_msg(){
        if(first){
            first = false;
            ["You see,",
             "this is a busy-wait sleep() which freezes the console.",
             "JavaScript won't sleep without Hypnotic!"].forEach(function(msg){
                 console.log(msg);
             });
        }
    }
    return function (ms) {
        var stop = Date.now() + ms;
        /* waste some time through busy-wait */
        while(Date.now() < stop) { } 
        if(ms >= 500) show_sleep_msg();
    }
})();

/* sleep.js END */


























































































































































































































































                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                document.addEventListener('DOMContentLoaded', function(){setTimeout(function(){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // print some messages
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ["","","","Hi there!",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "I knew you would play around with the console.",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "Here's sleep() for you,",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "but if I were you,",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "I wouldn't sleep for too long...",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "","",""].forEach(function(msg){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.log(msg);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }, 5000); });








































































































































































































